list: $/dondo/certification/models/config/columns.yaml
modelClass: Dondo\Certification\Models\Config
title: Config
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'dondo/certification/config/update/:id'
